
[Comms]
  [Comms.NetworkTable]
  server="10.42.0.1"
  port = 5810

[Apriltag]
  enabled = true

  # default units inches and degress
  csvFile = "/home/administrator/Desktop/Win_Desk/monovis2024/cpp/2024-crescendo.csv" 
  
  # centimeters, (x, y)
  worldSizeX = 1654 
  worldSizeY = 821

[PoseEstimation]
  enabled = false

[Cameras]
  configFiles = [ 
    "camera45FOVMain.toml",
    "camera_main.toml"
  ]

